### ISSUE TITLE
limortaccitua

### ISSUE THREAD

**Issue by stefanosalvucci** [linkgod/SHA-1#7]
you shouldn't update your public package without versioning

**Comment by linkgod** [comment]
Sorry, I updated the first version number.

Excuse me, what problem did you encounter? How can I solve it?

**Comment by FernandoVelcic** [comment]
I had angulartics in my project using bower, that it uses your extension https://github.com/angulartics/angulartics/blob/master/bower.json your change broke my deploy system

**Comment by linkgod** [comment]
> I had angulartics in my project using bower, that uses your extension https://github.com/angulartics/angulartics/blob/master/bower.json your change broke my deploy system

Sorry, I didn't notice the bower problem.
I tried to fix it, can you please help me to see if it is successful?

Please be careful to clear some cache
```
bower cache clean
```

**Comment by FernandoVelcic** [comment]
> > I had angulartics in my project using bower, that uses your extension https://github.com/angulartics/angulartics/blob/master/bower.json your change broke my deploy system
> 
> Sorry, I didn't notice the bower problem.
> I tried to [fix it](https://github.com/linkgod/SHA-1/commit/b51b81ce8f0629a11557c37e91a891a6a8625e19), can you please help me to see if it is successful?
> 
> Please be careful to clear some cache
> 
> ```
> bower cache clean
> ```

Thanks, now it works again!
